// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMlE1VmCzXy4_FDo7mWQfE0nMYOVBCnc',
    appId: '1:437978448933:web:323034797cf787ac3c2bcc',
    messagingSenderId: '437978448933',
    projectId: 'spacex-e632a',
    authDomain: 'spacex-e632a.firebaseapp.com',
    storageBucket: 'spacex-e632a.appspot.com',
    measurementId: 'G-K141YDQB83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXiWW2NaxClGBwuuk-BnIanlDITTHWF0',
    appId: '1:437978448933:android:2f363cb995745a483c2bcc',
    messagingSenderId: '437978448933',
    projectId: 'spacex-e632a',
    storageBucket: 'spacex-e632a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyJkncxtxECCHHkWT1BXCtxU2QHf2Plzo',
    appId: '1:437978448933:ios:7e8dff1151c3cc623c2bcc',
    messagingSenderId: '437978448933',
    projectId: 'spacex-e632a',
    storageBucket: 'spacex-e632a.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyJkncxtxECCHHkWT1BXCtxU2QHf2Plzo',
    appId: '1:437978448933:ios:7e8dff1151c3cc623c2bcc',
    messagingSenderId: '437978448933',
    projectId: 'spacex-e632a',
    storageBucket: 'spacex-e632a.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvMlE1VmCzXy4_FDo7mWQfE0nMYOVBCnc',
    appId: '1:437978448933:web:925c9b146dee2b6a3c2bcc',
    messagingSenderId: '437978448933',
    projectId: 'spacex-e632a',
    authDomain: 'spacex-e632a.firebaseapp.com',
    storageBucket: 'spacex-e632a.appspot.com',
    measurementId: 'G-V4E6DJ1K9T',
  );
}
